#Description:derenzo phantom with all the materials setting to vacuum 
# to eliminate the effects of scaater and attenuation.
# ### the outer cylinder dimater is 180mm and
###the diameter of the wells are: 6.0, 4.5, 3, 2.4, 1.6, 1mm.

#Editor:Bo Ma
#date:2020-05-16
#Email:mabo@ihep.ac.cn
#Tel:010-88235869
#Cell:15210606357

#Version:v1.0
#---------------

 
#       P H A N T O M   G E O M E T R Y
/gate/world/daughters/name cyl_phantom
/gate/world/daughters/insert cylinder
/gate/cyl_phantom/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cyl_phantom/geometry/setRmax 9.0 cm
/gate/cyl_phantom/geometry/setRmin  0.0 cm
/gate/cyl_phantom/geometry/setHeight 20.0 cm
/gate/cyl_phantom/geometry/setPhiStart 0. deg
/gate/cyl_phantom/geometry/setDeltaPhi 360. deg
/gate/cyl_phantom/setMaterial Vacuum
/gate/cyl_phantom/vis/forceWireframe
#/gate/cyl_phantom/vis/forceSolid
/gate/cyl_phantom/vis/setColor green
/gate/cyl_phantom/vis/setVisible 1


#      A t t a c h   P h a n t o m
/gate/cyl_phantom/attachPhantomSD

